import { Prisma } from "@prisma/client";
import { writeAuditLog } from "@/lib/audit/write";
import { AuditAction } from "@/lib/audit/helpers";

type Tx = Prisma.TransactionClient;

// Per-location order numbers are generated by reading max(orderNumber) + 1.
// Under concurrent checkouts, two transactions can read the same max and
// attempt to insert the same number. The @@unique constraint catches this,
// but we retry up to 3 times with jitter to avoid surfacing P2002 to callers.
// The unique constraint is the actual safety net; this is convenience.
export async function withOrderNumberRetry<T>(
  fn: () => Promise<T>,
  maxRetries = 3,
): Promise<T> {
  let lastError: unknown;
  for (let i = 0; i < maxRetries; i++) {
    try {
      return await fn();
    } catch (err) {
      if (
        err instanceof Prisma.PrismaClientKnownRequestError &&
        err.code === "P2002" &&
        (err.meta?.target as string[] | undefined)?.includes("orderNumber")
      ) {
        lastError = err;
        await new Promise((r) =>
          setTimeout(r, 10 + Math.floor(Math.random() * 40)),
        );
        continue;
      }
      throw err;
    }
  }
  throw lastError;
}

/**
 * Convert a Cart to an Order. Atomic operation:
 * 1. Generate per-location order number
 * 2. Copy CartItems → OrderItems
 * 3. Mark Cart as PENDING_PAYMENT
 * 4. Create Order with snapshot of all cart fields
 *
 * Retries up to 3 times on order number collision (P2002).
 */
export async function finalizeCartToOrder(
  tx: Tx,
  args: {
    organizationId: string;
    cartId: string;
    clientNameSnapshot: string | null;
    receiptEmail: string | null;
    receiptPhone: string | null;
  },
): Promise<{ orderId: string; orderNumber: string }> {
  return withOrderNumberRetry(async () => {
    const cart = await tx.cart.findFirst({
      where: {
        id: args.cartId,
        organizationId: args.organizationId,
        status: "OPEN",
      },
    });
    if (!cart) {
      throw new Error("Cart not found or not OPEN");
    }

    const cartItems = await tx.cartItem.findMany({
      where: { cartId: cart.id },
      orderBy: { displayOrder: "asc" },
    });

    // Generate order number (per-location sequence starting at 1001)
    const lastOrder = await tx.order.findFirst({
      where: { locationId: cart.locationId },
      orderBy: { createdAt: "desc" },
      select: { orderNumber: true },
    });
    const nextNumber = lastOrder
      ? String(parseInt(lastOrder.orderNumber) + 1)
      : "1001";

    const order = await tx.order.create({
      data: {
        organizationId: cart.organizationId,
        locationId: cart.locationId,
        cartId: cart.id,
        orderNumber: nextNumber,
        appointmentId: cart.appointmentId,
        clientId: cart.clientId,
        clientNameSnapshot: args.clientNameSnapshot,
        subtotalCents: cart.subtotalCents,
        discountCents: cart.discountCents,
        taxCents: cart.taxCents,
        tipCents: cart.tipCents,
        giftCardAppliedCents: cart.giftCardAppliedCents,
        loyaltyAppliedCents: cart.loyaltyAppliedCents,
        depositAppliedCents: cart.depositAppliedCents,
        totalCents: cart.totalCents,
        balanceDueCents: cart.totalCents,
        status: "OPEN",
        receiptEmail: args.receiptEmail,
        receiptPhone: args.receiptPhone,
      },
    });

    for (const ci of cartItems) {
      await tx.orderItem.create({
        data: {
          orderId: order.id,
          itemType: ci.itemType,
          displayName: ci.displayName,
          serviceId: ci.serviceId,
          appointmentItemId: ci.appointmentItemId,
          staffId: ci.staffId,
          quantity: ci.quantity,
          unitPriceCents: ci.unitPriceCents,
          discountCents: ci.discountCents,
          subtotalCents: ci.subtotalCents,
          taxableFlag: ci.taxableFlag,
          taxCents: ci.taxCents,
          isAddOn: ci.isAddOn,
          displayOrder: ci.displayOrder,
        },
      });
    }

    await tx.cart.update({
      where: { id: cart.id },
      data: { status: "PENDING_PAYMENT", updatedAt: new Date() },
    });

    await writeAuditLog({
      userId: null,
      organizationId: cart.organizationId,
      action: AuditAction.ORDER_CREATE,
      entity: "Order",
      entityId: order.id,
      after: { orderNumber: nextNumber, totalCents: cart.totalCents },
    });

    return { orderId: order.id, orderNumber: nextNumber };
  });
}

/**
 * Apply a payment to an order. Updates paidCents, balanceDueCents, status.
 */
export async function recordPaymentOnOrder(
  tx: Tx,
  args: {
    organizationId: string;
    orderId: string;
    paymentAmountCents: number;
  },
): Promise<{ newPaidCents: number; newBalanceDue: number; newStatus: string }> {
  const order = await tx.order.findFirst({
    where: { id: args.orderId, organizationId: args.organizationId },
    select: { paidCents: true, totalCents: true, status: true, cartId: true },
  });
  if (!order) {
    throw new Error("Order not found");
  }

  const newPaidCents = order.paidCents + args.paymentAmountCents;
  const newBalanceDue = Math.max(0, order.totalCents - newPaidCents);
  let newStatus = order.status;
  if (newBalanceDue <= 0) {
    newStatus = "PAID";
  } else if (newPaidCents > 0) {
    newStatus = "PARTIALLY_PAID";
  }

  await tx.order.update({
    where: { id: args.orderId },
    data: {
      paidCents: newPaidCents,
      balanceDueCents: newBalanceDue,
      status: newStatus,
      closedAt: newStatus === "PAID" ? new Date() : null,
      updatedAt: new Date(),
    },
  });

  if (newStatus === "PAID" && order.cartId) {
    await tx.cart.update({
      where: { id: order.cartId },
      data: { status: "PAID", updatedAt: new Date() },
    });
  }

  return { newPaidCents, newBalanceDue, newStatus };
}
