// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Prisma ORM 7: connection URLs live here, not in schema.prisma.
  // Use DATABASE_URL (direct Postgres URL works for migrate + client; pooler-only URLs may need tuning).
  datasource: {
    url: env("DATABASE_URL"),
  },
});
