export type MarketingTrigger = 'CLIENT_BIRTHDAY' | 'FIRST_VISIT_ANNIVERSARY' | 'X_DAYS_SINCE_LAST_VISIT' | 'ABANDONED_BOOKING' | 'POST_APPOINTMENT' | 'WELCOME_NEW_CLIENT' | 'AFTER_FIRST_NO_SHOW' | 'CUSTOM';
export type MarketingChannel = 'EMAIL' | 'SMS' | 'PUSH' | 'IN_APP' | 'EMAIL_AND_SMS';
export type ExecutionStatus = 'QUEUED' | 'SENT' | 'DELIVERED' | 'OPENED' | 'CLICKED' | 'BOUNCED' | 'FAILED' | 'UNSUBSCRIBED' | 'CONVERTED';
