import type { VerticalConfig } from "../types";

export const salonConfig: VerticalConfig = {
  id: 'salon',
  displayName: 'Salon & Beauty',
  tagline: 'Full-service hair, color, and beauty',

  terms: {
    staff: 'Stylist',
    staffPlural: 'Stylists',
    client: 'Guest',
    clientPlural: 'Guests',
    service: 'Service',
    servicePlural: 'Services',
    location: 'Salon',
    locationPlural: 'Salons',
    appointment: 'Appointment',
    appointmentPlural: 'Appointments',
  },

  features: {
    colorStudio: true,
    formulaCards: true,
    commissionTracking: true,
    waiverForms: true,
    boothRent: false,
    walkInQueue: false,
    msdsLog: false,
    medicalIntake: false,
    injectableTracking: false,
    hipaaMode: false,
    tableManagement: false,
    kitchenDisplay: false,
    recipeBasedInventory: false,
    onlineOrdering: false,
    deliveryIntegrations: false,
    kdsDisplay: false,
    membershipBilling: false,
    classScheduling: false,
    classPasses: false,
    vehicleProfiles: false,
    petProfiles: false,
    vaccinationTracking: false,
    aiReceptionist: true,
    inventoryTracking: true,
    loyaltyProgram: true,
    giftCards: true,
    onlineBooking: true,
  },

  navigation: [
    { id: 'dashboard', label: 'Dashboard', icon: 'LayoutDashboard', route: '/dashboard' },
    {
      id: 'appointments',
      label: 'Appointments',
      icon: 'Calendar',
      route: '/dashboard/appointments',
      children: [
        { id: 'calendar', label: 'Calendar', icon: 'CalendarDays', route: '/dashboard/appointments/calendar' },
        { id: 'today', label: "Today's Schedule", icon: 'Clock', route: '/dashboard/appointments/today' },
        { id: 'waitlist', label: 'Waitlist', icon: 'ListOrdered', route: '/dashboard/appointments/waitlist' },
      ],
    },
    {
      id: 'clients',
      label: 'Guests',
      icon: 'Users',
      route: '/dashboard/clients',
      children: [
        { id: 'clients-list', label: 'All Guests', icon: 'List', route: '/dashboard/clients' },
        { id: 'relationship', label: 'Relationship Scores', icon: 'Heart', route: '/dashboard/clients/relationships' },
        { id: 'winback', label: 'Win-Back', icon: 'RefreshCw', route: '/dashboard/clients/winback' },
      ],
    },
    {
      id: 'stylists',
      label: 'Stylists',
      icon: 'Scissors',
      route: '/dashboard/stylists',
      children: [
        { id: 'schedule', label: 'Schedule', icon: 'CalendarClock', route: '/dashboard/stylists/schedule' },
        { id: 'commissions', label: 'Commissions', icon: 'DollarSign', route: '/dashboard/stylists/commissions', requiresFeature: 'commissionTracking' },
        { id: 'performance', label: 'Performance', icon: 'TrendingUp', route: '/dashboard/stylists/performance' },
      ],
    },
    {
      id: 'color-studio',
      label: 'Color Studio',
      icon: 'Palette',
      route: '/dashboard/color-studio',
      requiresFeature: 'colorStudio',
      children: [
        { id: 'formulas', label: 'Formula Library', icon: 'BookOpen', route: '/dashboard/color-studio/formulas' },
        { id: 'before-after', label: 'Before/After', icon: 'Images', route: '/dashboard/color-studio/before-after' },
        { id: 'color-analytics', label: 'Analytics', icon: 'BarChart3', route: '/dashboard/color-studio/analytics' },
      ],
    },
    { id: 'services', label: 'Services', icon: 'Sparkles', route: '/dashboard/services' },
    { id: 'inventory', label: 'Inventory', icon: 'Package', route: '/dashboard/inventory', requiresFeature: 'inventoryTracking' },
    { id: 'pos', label: 'POS', icon: 'CreditCard', route: '/dashboard/pos' },
    { id: 'reports', label: 'Reports', icon: 'BarChart2', route: '/dashboard/reports' },
    { id: 'marketing', label: 'Marketing', icon: 'Megaphone', route: '/dashboard/marketing' },
    { id: 'ai-receptionist', label: 'AI Receptionist', icon: 'Bot', route: '/dashboard/ai-receptionist', requiresFeature: 'aiReceptionist' },
    { id: 'settings', label: 'Settings', icon: 'Settings', route: '/dashboard/settings' },
  ],

  dashboardWidgets: [
    { id: 'revenue-today', order: 1 },
    { id: 'appointments-today', order: 2 },
    { id: 'rebook-rate', order: 3 },
    { id: 'top-stylists', order: 4 },
    { id: 'recent-guests', order: 5 },
    { id: 'inventory-alerts', order: 6, requiresFeature: 'inventoryTracking' },
  ],

  defaultServices: [
    { name: "Women's Haircut", durationMinutes: 45, priceCents: 6500, category: 'Haircuts' },
    { name: "Men's Haircut", durationMinutes: 30, priceCents: 3500, category: 'Haircuts' },
    { name: "Kids' Haircut", durationMinutes: 30, priceCents: 2500, category: 'Haircuts' },
    { name: 'Single Process Color', durationMinutes: 90, priceCents: 8500, category: 'Color' },
    { name: 'Partial Highlights', durationMinutes: 120, priceCents: 12000, category: 'Color' },
    { name: 'Full Highlights', durationMinutes: 150, priceCents: 14500, category: 'Color' },
    { name: 'Balayage', durationMinutes: 180, priceCents: 20000, category: 'Color' },
    { name: 'Blowout', durationMinutes: 30, priceCents: 4000, category: 'Styling' },
    { name: 'Special Occasion Style', durationMinutes: 60, priceCents: 7500, category: 'Styling' },
    { name: 'Deep Conditioning Treatment', durationMinutes: 30, priceCents: 3500, category: 'Treatments' },
    { name: 'Keratin Treatment', durationMinutes: 150, priceCents: 25000, category: 'Treatments' },
  ],

  onboardingChecklist: [
    { id: 'business-info', title: 'Complete business information', description: 'Add your salon name, address, and contact details', route: '/dashboard/settings#about' },
    { id: 'first-stylist', title: 'Add your first stylist', description: 'Invite at least one team member', route: '/dashboard/stylists/new', completionCheck: 'staff' },
    { id: 'services', title: 'Set up your service menu', description: 'Customize the starter services or add your own', route: '/dashboard/services', completionCheck: 'services' },
    { id: 'payment', title: 'Connect payment processing', description: 'Set up Kasse Pay to accept card payments', route: '/dashboard/settings#payment_methods', completionCheck: 'paymentMethod' },
    { id: 'hours', title: 'Set business hours', description: "Tell guests when you're open", route: '/dashboard/settings#hours' },
    { id: 'online-booking', title: 'Enable online booking', description: 'Let guests book themselves 24/7', route: '/dashboard/settings#online_booking' },
    { id: 'first-client', title: 'Add your first guest', description: 'Import from your previous system or add manually', route: '/dashboard/clients/new', completionCheck: 'clients' },
  ],

  compliance: {
    licenseRequired: true,
    licenseType: 'TDLR Cosmetology License',
    waiverRequired: true,
    waiverContext: 'Chemical services (color, perm, relaxer, keratin) require a signed waiver before treatment.',
    hipaaRequired: false,
    staffCertifications: ['Cosmetology', 'Hair Color Specialist', 'Master Stylist'],
  },

  recommendedAddons: [
    'ai_receptionist_standard',
    'kasse_color_standard',
    'sms_pack_1k',
    'chemical_waivers_enhanced',
    'tdlr_license_verify',
  ],

  typicalPlan: 'GROWTH',
  averageAddonRevenueCents: 14900,
};
